// src/styles/theme.ts
import { StyleSheet, Platform } from 'react-native';

// Cores do sistema
export const colors = {
  accent: '#00E5A0',
  accentWarn: '#FFB830',
  accentErr: '#FF4D6D',
  bg: '#0A0A0F',
  surface: '#14141C',
  surface2: '#1E1E2A',
  text: '#F0F0F8',
  textDim: '#6B6B88',
} as const;

// Estilos comuns (reutilizáveis)
export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bg,
  },
  loadingText: {
    marginTop: 16,
    color: colors.textDim,
    fontSize: 16,
  },
  errorText: {
    color: colors.accentErr,
    fontSize: 18,
    marginBottom: 20,
  },
  errorButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
  },
  errorButtonText: {
    color: '#000',
    fontWeight: '700',
  },
});

// Estilos específicos da tela de scanner
export const scannerStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 56 : 36,
    paddingBottom: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff0A',
  },
  backBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backBtnText: {
    fontSize: 22,
    color: colors.text,
  },
  headerCenter: {
    flex: 1,
    marginHorizontal: 12,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 0.2,
  },
  headerSub: {
    fontSize: 11,
    color: colors.textDim,
    marginTop: 1,
  },
  finishBtn: {
    backgroundColor: colors.accent + '22',
    borderWidth: 1,
    borderColor: colors.accent + '55',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
  },
  finishBtnText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '600',
  },
  progressSection: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff08',
  },
  progressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 6,
  },
  progressLabel: {
    fontSize: 12,
    color: colors.textDim,
    fontWeight: '500',
  },
  progressCount: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.accent,
  },
  progressTotal: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.textDim,
  },
  progressTrack: {
    height: 6,
    backgroundColor: '#ffffff0F',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.accent,
    borderRadius: 3,
  },
  progressFillComplete: {
    backgroundColor: '#00FF99',
  },
  progressPct: {
    fontSize: 11,
    color: colors.textDim,
    textAlign: 'right',
    marginTop: 4,
  },
  alertsContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 160 : 140,
    left: 16,
    right: 16,
    zIndex: 100,
    gap: 6,
  },
  alertBanner: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderLeftWidth: 4,
  },
  alert_success: {
    backgroundColor: colors.accent + '22',
    borderLeftColor: colors.accent,
  },
  alert_warning: {
    backgroundColor: colors.accentWarn + '22',
    borderLeftColor: colors.accentWarn,
  },
  alert_error: {
    backgroundColor: colors.accentErr + '22',
    borderLeftColor: colors.accentErr,
  },
  alertText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '500',
  },
  tabs: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingBottom: 0,
    gap: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: {
    borderBottomColor: colors.accent,
  },
  tabText: {
    fontSize: 13,
    color: colors.textDim,
    fontWeight: '500',
  },
  tabTextActive: {
    color: colors.accent,
    fontWeight: '700',
  },
  mainArea: {
    flex: 1,
  },
  cameraWrapper: {
    flex: 1,
    backgroundColor: '#000',
    overflow: 'hidden',
  },
  cameraPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.surface,
    gap: 12,
  },
  cameraPlaceholderIcon: {
    fontSize: 48,
  },
  cameraPlaceholderText: {
    color: colors.textDim,
    fontSize: 15,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  permissionBtn: {
    backgroundColor: colors.accent,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    marginTop: 8,
  },
  permissionBtnText: {
    color: '#000',
    fontWeight: '700',
    fontSize: 14,
  },
  viewfinder: {
    position: 'absolute',
    top: '20%',
    left: '12%',
    right: '12%',
    bottom: '25%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  corner: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderColor: colors.accent,
    borderWidth: 3,
  },
  cornerTL: {
    top: 0,
    left: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  cornerTR: {
    top: 0,
    right: 0,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  cornerBL: {
    bottom: 0,
    left: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  cornerBR: {
    bottom: 0,
    right: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  scanLine: {
    width: '80%',
    height: 2,
    backgroundColor: colors.accent,
    opacity: 0.6,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  cameraHint: {
    position: 'absolute',
    bottom: 24,
    alignSelf: 'center',
    color: colors.textDim,
    fontSize: 13,
    backgroundColor: '#00000066',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: 'hidden',
  },
  manualArea: {
    flex: 1,
    backgroundColor: colors.surface,
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manualIcon: {
    fontSize: 52,
    marginBottom: 16,
  },
  manualTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  manualDesc: {
    fontSize: 14,
    color: colors.textDim,
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 20,
  },
  manualInput: {
    width: '100%',
    backgroundColor: colors.surface2,
    borderWidth: 1.5,
    borderColor: '#ffffff15',
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    fontSize: 18,
    color: colors.text,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 2,
    marginBottom: 16,
  },
  manualSubmitBtn: {
    width: '100%',
    backgroundColor: colors.accent,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  manualSubmitDisabled: {
    opacity: 0.35,
  },
  manualSubmitText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '800',
  },
  lastScannedCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: colors.surface2,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.accent + '33',
  },
  lastScannedLabel: {
    fontSize: 10,
    color: colors.accent,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  lastScannedCode: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 2,
  },
  lastScannedDesc: {
    fontSize: 13,
    color: colors.textDim,
    marginBottom: 2,
  },
  lastScannedMeta: {
    fontSize: 12,
    color: colors.textDim,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: '#00000088',
  },
  modalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    maxHeight: '80%',
    borderTopWidth: 1,
    borderColor: '#ffffff0A',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#ffffff22',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 13,
    color: colors.textDim,
    marginBottom: 20,
  },
  modalDetails: {
    maxHeight: 300,
  },
  modalDetailsContent: {
    gap: 2,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff08',
    gap: 12,
  },
  detailIcon: {
    fontSize: 18,
    width: 24,
    textAlign: 'center',
    marginTop: 1,
  },
  detailContent: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 11,
    color: colors.textDim,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  detailValue: {
    fontSize: 15,
    color: colors.text,
    fontWeight: '500',
  },
  detailValueHighlight: {
    color: colors.accent,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 1,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  cancelBtn: {
    flex: 1,
    backgroundColor: colors.surface2,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff10',
  },
  cancelBtnText: {
    color: colors.textDim,
    fontSize: 15,
    fontWeight: '600',
  },
  confirmBtn: {
    flex: 2,
    backgroundColor: colors.accent,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  confirmBtnText: {
    color: '#000',
    fontSize: 15,
    fontWeight: '800',
  },
});

// Estilos específicos da tela de lista de inventários
export const inventoryListStyles = StyleSheet.create({
  header: {
    paddingTop: Platform.OS === 'ios' ? 56 : 36,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff0A',
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 13,
    color: colors.textDim,
    marginTop: 2,
  },
  listContent: {
    padding: 16,
    paddingBottom: 110,
  },
  listContentEmpty: {
    flex: 1,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#ffffff0A',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  cardHeaderLeft: {
    flex: 1,
    marginRight: 12,
  },
  cardName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 3,
  },
  cardDate: {
    fontSize: 12,
    color: colors.textDim,
  },
  cardHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  completeBadge: {
    backgroundColor: colors.accent + '22',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: colors.accent + '44',
  },
  completeBadgeText: {
    fontSize: 11,
    color: colors.accent,
    fontWeight: '700',
  },
  deleteBtn: {
    padding: 4,
  },
  deleteBtnText: {
    fontSize: 16,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 6,
  },
  statsLabel: {
    fontSize: 12,
    color: colors.textDim,
  },
  statsCount: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.accent,
  },
  statsCountComplete: {
    color: '#00FF99',
  },
  statsTotal: {
    fontSize: 13,
    fontWeight: '400',
    color: colors.textDim,
  },
  progressTrack: {
    height: 6,
    backgroundColor: '#ffffff0F',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.accent,
    borderRadius: 3,
  },
  progressFillComplete: {
    backgroundColor: '#00FF99',
  },
  pctLabel: {
    fontSize: 11,
    color: colors.textDim,
    textAlign: 'right',
    marginTop: 4,
  },
  pctLabelComplete: {
    color: '#00FF99',
  },
  statsError: {
    fontSize: 13,
    color: colors.accentErr,
  },
  fab: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 36 : 24,
    right: 20,
    left: 20,
    backgroundColor: colors.accent,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  fabIcon: {
    fontSize: 20,
    color: '#000',
    fontWeight: '800',
    lineHeight: 22,
  },
  fabLabel: {
    fontSize: 16,
    color: '#000',
    fontWeight: '800',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 80,
  },
  emptyIcon: {
    fontSize: 52,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  emptyDesc: {
    fontSize: 14,
    color: colors.textDim,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
});

// Estilos específicos da tela de detalhe do inventário
export const inventoryDetailStyles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.bg,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  loadingText: {
    color: colors.textDim,
    fontSize: 15,
    marginTop: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 56 : 36,
    paddingBottom: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff0A',
  },
  backBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backBtnText: {
    fontSize: 22,
    color: colors.text,
  },
  headerCenter: {
    flex: 1,
    marginHorizontal: 10,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  headerSub: {
    fontSize: 11,
    color: colors.textDim,
    marginTop: 2,
  },
  resetBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resetBtnText: {
    fontSize: 20,
    color: colors.textDim,
  },
  statsSection: {
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff08',
  },
  statsCards: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
    marginTop: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface2,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  statCardLabel: {
    fontSize: 10,
    color: colors.textDim,
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statCardValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.text,
  },
  statCardValueAccent: {
    color: colors.accent,
  },
  statCardValueWarn: {
    color: colors.accentWarn,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressTrack: {
    flex: 1,
    height: 6,
    backgroundColor: '#ffffff0F',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.accent,
    borderRadius: 3,
  },
  progressFillComplete: {
    backgroundColor: '#00FF99',
  },
  progressPct: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.accent,
    minWidth: 38,
    textAlign: 'right',
  },
  progressPctComplete: {
    color: '#00FF99',
  },
  completeBanner: {
    marginTop: 12,
    backgroundColor: colors.accent + '18',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.accent + '33',
  },
  completeBannerText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  searchSection: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: colors.bg,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#ffffff0A',
    gap: 8,
  },
  searchIcon: {
    fontSize: 14,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 11,
    fontSize: 14,
    color: colors.text,
  },
  filterTabs: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginBottom: 8,
    gap: 8,
  },
  filterTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#ffffff0A',
  },
  filterTabActive: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '55',
  },
  filterTabText: {
    fontSize: 12,
    color: colors.textDim,
    fontWeight: '500',
  },
  filterTabTextActive: {
    color: colors.accent,
    fontWeight: '700',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 110,
  },
  listContentEmpty: {
    flex: 1,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 60,
  },
  emptyIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  emptyText: {
    color: colors.textDim,
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  itemRow: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginBottom: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ffffff0A',
  },
  itemRowScanned: {
    borderColor: colors.accent + '22',
  },
  itemIndicator: {
    width: 4,
    backgroundColor: '#ffffff10',
  },
  itemIndicatorScanned: {
    backgroundColor: colors.accent,
  },
  itemContent: {
    flex: 1,
    padding: 12,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  itemCode: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  scannedBadge: {
    backgroundColor: colors.accent + '22',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  scannedBadgeText: {
    fontSize: 10,
    color: colors.accent,
    fontWeight: '700',
  },
  pendingBadge: {
    backgroundColor: '#ffffff0A',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  pendingBadgeText: {
    fontSize: 10,
    color: colors.textDim,
    fontWeight: '600',
  },
  itemDesc: {
    fontSize: 13,
    color: colors.textDim,
    marginBottom: 6,
  },
  itemMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  itemMetaText: {
    fontSize: 11,
    color: colors.textDim,
  },
  scanFab: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 36 : 24,
    right: 20,
    left: 20,
    backgroundColor: colors.accent,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 10,
  },
  scanFabComplete: {
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.accent + '55',
  },
  scanFabIcon: {
    fontSize: 16,
    color: '#000',
    fontWeight: '800',
  },
  scanFabLabel: {
    fontSize: 16,
    color: '#000',
    fontWeight: '800',
  },
});

export const homeStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 56 : 36,
    paddingBottom: 14,
    paddingHorizontal: 20,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff0A',
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 13,
    color: colors.textDim,
    marginTop: 2,
  },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accent + '22',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.accent + '44',
  },
  addBtnText: {
    fontSize: 20,
    color: colors.accent,
    lineHeight: 24,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#ffffff0A',
    gap: 8,
  },
  searchIcon: {
    fontSize: 14,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 11,
    fontSize: 14,
    color: colors.text,
  },
  filterBtn: {
    width: 46,
    backgroundColor: colors.surface,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff0A',
  },
  filterBtnActive: {
    borderColor: colors.accent + '55',
    backgroundColor: colors.accent + '15',
  },
  filterBtnText: {
    fontSize: 18,
  },
  filterDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  activeFiltersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  chip: {
    backgroundColor: colors.accent + '18',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: colors.accent + '44',
  },
  chipText: {
    fontSize: 12,
    color: colors.accent,
    fontWeight: '600',
  },
  chipClear: {
    backgroundColor: '#FF4D6D18',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#FF4D6D44',
  },
  chipClearText: {
    fontSize: 12,
    color: '#FF4D6D',
    fontWeight: '600',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 13,
    borderRadius: 12,
  },
  actionBtnPrimary: {
    backgroundColor: colors.accent,
  },
  actionBtnSecondary: {
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.accent + '44',
  },
  actionBtnIcon: {
    fontSize: 15,
    color: '#000',
    fontWeight: '800',
  },
  actionBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#000',
  },
  counterRow: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  counterText: {
    fontSize: 13,
    color: colors.textDim,
  },
  counterNum: {
    fontWeight: '700',
    color: colors.text,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  listContentEmpty: {
    flex: 1,
  },
  footerLoader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  footerLoaderText: {
    fontSize: 13,
    color: colors.textDim,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 60,
  },
  emptyIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  emptyDesc: {
    fontSize: 14,
    color: colors.textDim,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  itemRow: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginBottom: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ffffff0A',
  },
  itemRowScanned: {
    borderColor: colors.accent + '22',
  },
  itemIndicator: {
    width: 4,
    backgroundColor: '#ffffff10',
  },
  itemIndicatorScanned: {
    backgroundColor: colors.accent,
  },
  itemBody: {
    flex: 1,
    padding: 12,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  itemCode: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  badgeOk: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.accent + '22',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeOkText: {
    fontSize: 11,
    color: colors.accent,
    fontWeight: '800',
  },
  badgePending: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#ffffff0A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgePendingText: {
    fontSize: 11,
    color: colors.textDim,
  },
  itemDesc: {
    fontSize: 13,
    color: colors.textDim,
    marginBottom: 6,
  },
  itemMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  itemMetaText: {
    fontSize: 11,
    color: colors.textDim,
  },
  itemMetaInv: {
    fontSize: 11,
    color: colors.accent + 'AA',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#00000077',
  },
  modalSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    maxHeight: '75%',
    borderTopWidth: 1,
    borderColor: '#ffffff0A',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#ffffff22',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 18,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 16,
  },
  filterGroupLabel: {
    fontSize: 11,
    color: colors.textDim,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
    marginTop: 4,
  },
  filterOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  filterOption: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: '#ffffff0A',
  },
  filterOptionActive: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '55',
  },
  filterOptionText: {
    fontSize: 13,
    color: colors.textDim,
    fontWeight: '500',
  },
  filterOptionTextActive: {
    color: colors.accent,
    fontWeight: '700',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  btnClear: {
    flex: 1,
    backgroundColor: colors.surface2,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff10',
  },
  btnClearText: {
    color: colors.textDim,
    fontSize: 14,
    fontWeight: '600',
  },
  btnApply: {
    flex: 2,
    backgroundColor: colors.accent,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  btnApplyText: {
    color: '#000',
    fontSize: 14,
    fontWeight: '800',
  },
});



